baseURL = "https://diego-ortiz.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Diego Ortiz"

theme = 'jimtheme'

[markup.highlight]
lineNos = true

[params.social]
LinkedIn = "diegoortizmatajira"
GitHub = "diegoortizmatajira"
